#!/bin/bash bingmsg
#=======================================================================
#: FILE: bing-bash
#: PATH: $BING/func/bing-bash
#: TYPE: environment
#:
#: AUTHOR:
#:      bing-bash by Ivan Ilic <ivanilic1975@gmail.com>
#:      https://github.com/mandober/bing-bash
#:      za Ǆ - Use freely at owns risk
#:      25-Mar-2016 (last revision)
#:
#: DESCRIPTION: 
#:      Configuration and initialization settings.
#:
#=======================================================================

#
#   BASE VARS
#
# These are all convenience vars, none are required.

# [bing-bash] root directory
export BING="$HOME/bing"

# [bing-bash] main functions' directory
export BING_FUNC="$BING/func"

# [bing-bash] temporary directory
export BING_TEMP="$BING/temp"

# [bing-bash] path to sqlite db 
export BING_DB="$BING_FUNC/sys/bb.db"

# [bing-bash] name of table in sqlite db
export BING_TBL=funcs


#
#   FPATH
#
# FPATH is an environment variable, similar to PATH, containing
# colon-delimited paths to functions' directories. Bash doesn't
# have this directory natively set as other shells that support
# functions autoloading do. Subroutines that deal with function
# (auto)loading (those in the `load' file) use FPATH. Functions
# autoloading is simulated by using an eponymous function which
# loads the real function's definition on function's first call
export FPATH=$BING_FUNC:$BING_FUNC/strings:$BING_FUNC/sys


#
#   DEBUG
#
# If enabled bb_err function will print debugging messages.
# Temporary, until integrated into BING_BASH as a letter d
# @TODO: make BING var with letters, e.g. BING=vdc (where d
# is for debug, c for color, etc.)
export BING_DEBUG=1


#
#   SHOPT
#
shopt -s extglob 		# enable extended regular exp
shopt -s extquote		# enables $'' and $"" quoting
shopt -s globstar       # enable ** matching
shopt -u nocasematch 	# case sensitivity with regexp
shopt -u nocaseglob     # case sensitivity when globbing
set +o noglob           # just in case it's unset
set +a 
# save current shell options
# set +o >| "$BING_TEMP/env_set"
# shopt -p >| "$BING_TEMP/env_shopt"


#
#   FUNCTIONS
#

# Always load
[[ -r "$BING_FUNC/load" ]] && . "$BING_FUNC/load"
[[ -r "$BING_FUNC/err" ]] && . "$BING_FUNC/err" # soon to be deprecated

# FUNCS
# Indexed array of function files
declare -a FUNCS=( $BING_FUNC/**/*.bash )


#
#   AUTOLOAD
#
bb_load --auto "${FUNCS[@]}"


#
#   INSERT IN DB (one time only)
#
# if [[ -r "$BING_FUNC/sql" ]]; then
# 	. "$BING_FUNC/sql"
# 	bb_sql --insert "${FUNCS[@]}"
# fi


#
#   FUNCTION ALIASES
#
[[ -r "$BING_FUNC/bing_aliases" ]] && . "$BING_FUNC/bing_aliases"


#
#   FUNCTIONS COMPLETIONS
#
complete -o default -o bashdefault -o nospace -A variable -A function echo


#
#   DATA SAMPLE
#
[[ -r "$BING_FUNC/bing_samples" ]] && . "$BING_FUNC/bing_samples"
