#!/bin/bash bingmsg
#==================================================================
#: FILE: bing_aliases
#: PATH: $BING_FUNC/bing_aliases
#: TYPE: aliases
#:
#: AUTHOR:
#:      bing-bash by mandober <zgag@yahoo.com>
#:      https://github.com/mandober/bing-bash
#:      za Ǆ - Use freely at owns risk
#:      26-Mar-2016 (last revision)
#:
#: DESCRIPTION:
#:      Aliases for bing-bash functions
#:
#==================================================================

alias typeof='bb_typeof'
alias explode='bb_explode'
alias implode='bb_implode'
alias range='bb_range'
alias array_clone="bb_array_clone"


# alias is='bb_is'
# alias get='bb_get'
# alias load='bb_load'

alias in_array='bb_in_array'

alias @='bb_array'
alias array='bb_array'



alias array_convert='bb_array_convert'
alias array_merge='bb_array_merge'
alias array_remove='bb_array_remove'
alias array_shift='bb_array_shift'
alias array_unique='bb_array_sort -u'
alias array_sort='bb_array_sort'
alias trim='bb_trim'
alias venn='bb_venn'
